### ISSUE TITLE
Error on running script

### ISSUE THREAD

**Issue by guywire** [gdsports/rpi-usb-host-midi-hub#2]
I'm getting this error:

`Verifying archive integrity...  100%   All good.
Uncompressing midihub  100%
creating directory in /etc/, moving midiconnect scripts there, setting permissio                                        ns...
create udev rule to run script on USB add/remove
running multimidicast
running midiconnect!
Traceback (most recent call last):
  File "/etc/rpi-midi-hub/midiconnect.py", line 18, in <module>
    client=re.search("client (\d*)\:", line)
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
TypeError: cannot use a string pattern on a bytes-like object
setup complete.

I can manually connect midi devices using aconnect.
Incidentally I get the same error trying to use the schuyberg script which I tried after.
I'm using a fresh install raspberry pi with bullseye

**Comment by AletheiaSound** [comment]
I get the same error. Any idea how to fix it?
I'm a complete beginner and this is the first code I'm trying to implement.

**Comment by jujumo** [comment]
Got the same. I am wondering if its a python version problem.
I see there is a fix proposal there https://github.com/gdsports/rpi-usb-host-midi-hub/pull/3
